import { StyleSheet } from 'react-native';

import type { WorldMapChromePadding } from '../map/WorldMap';

/** Согласовано с `mapResourceOverlay`: отступ для лого/компаса/«моё место» на `MapView`. */
export const HOME_MAP_CHROME_PADDING: WorldMapChromePadding = {
  top: 50,
  right: 56,
  bottom: 14,
  left: 10,
};

export const homeScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0c120c' },
  langScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  langSymbol: { fontSize: 56, marginBottom: 16 },
  langTitle: { fontSize: 36, fontWeight: '300', color: '#e8f5ea', letterSpacing: 2, marginBottom: 8 },
  langSub: { fontSize: 13, color: 'rgba(255,255,255,0.4)', marginBottom: 40, letterSpacing: 1 },
  langGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'center' },
  langBtn: {
    width: 80,
    height: 80,
    borderRadius: 16,
    backgroundColor: '#0f1a0f',
    borderWidth: 1,
    borderColor: '#1e3020',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  langFlag: { fontSize: 28 },
  langName: { fontSize: 11, color: 'rgba(255,255,255,0.5)', letterSpacing: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1a2a1a',
  },
  brand: { fontSize: 28, fontWeight: '300', color: '#e8f5ea', letterSpacing: 1 },
  brandGreen: { color: '#5aad6a' },
  level: { fontSize: 11, color: 'rgba(255,255,255,0.4)', marginTop: 2, letterSpacing: 2 },
  stats: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  stat: { alignItems: 'center' },
  statNum: { fontSize: 20, fontWeight: '600', color: '#e8c97a' },
  statNumGreen: { fontSize: 20, fontWeight: '600', color: '#5aad6a' },
  statLabel: { fontSize: 9, color: 'rgba(255,255,255,0.35)', letterSpacing: 1 },
  list: { flex: 1, padding: 20 },
  sectionTitle: { fontSize: 16, color: '#e8e4d8', fontWeight: '500', marginBottom: 16 },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f1a0f',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#1e3020',
  },
  cardEmoji: { fontSize: 28, marginRight: 14 },
  cardBody: { flex: 1 },
  cardTitle: { fontSize: 15, color: '#e8e4d8', fontWeight: '500' },
  cardDesc: { fontSize: 12, color: 'rgba(255,255,255,0.4)', marginTop: 3 },
  cardReward: { fontSize: 13, color: '#e8c97a', fontWeight: '600' },
  detail: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
  detailEmoji: { fontSize: 56, marginBottom: 16 },
  detailTitle: { fontSize: 22, color: '#e8e4d8', fontWeight: '500', textAlign: 'center', marginBottom: 6 },
  detailDesc: { fontSize: 13, color: 'rgba(255,255,255,0.45)', marginBottom: 14 },
  detailReward: { fontSize: 17, color: '#e8c97a', fontWeight: '600', marginBottom: 20 },
  steps: { width: '100%', marginBottom: 24 },
  stepsLabel: { fontSize: 10, letterSpacing: 2, color: 'rgba(255,255,255,0.3)', marginBottom: 10 },
  stepRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  stepNum: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(90,173,106,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumText: { fontSize: 11, color: '#5aad6a', fontWeight: '600' },
  stepText: { fontSize: 13, color: 'rgba(255,255,255,0.6)' },
  btnComplete: {
    backgroundColor: '#2d6a3f',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 40,
    marginBottom: 10,
  },
  btnCompleteText: { color: 'white', fontSize: 15, fontWeight: '600' },
  confirmRow: { width: '100%', alignItems: 'center', marginBottom: 10 },
  confirmText: { fontSize: 13, color: 'rgba(255,255,255,0.5)', marginBottom: 12 },
  confirmBtns: { flexDirection: 'row', gap: 10 },
  btnNo: { paddingVertical: 12, paddingHorizontal: 24, borderRadius: 12, borderWidth: 1, borderColor: '#1e3020' },
  btnNoText: { color: 'rgba(255,255,255,0.5)', fontSize: 14 },
  btnYes: { paddingVertical: 12, paddingHorizontal: 32, borderRadius: 12, backgroundColor: '#2d6a3f' },
  btnYesText: { color: 'white', fontSize: 14, fontWeight: '600' },
  btnBack: { padding: 12 },
  btnBackText: { color: 'rgba(255,255,255,0.4)', fontSize: 14 },
  empty: {
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    marginTop: 40,
    fontSize: 14,
    lineHeight: 22,
  },
  xpBarBg: {
    height: 18,
    backgroundColor: '#0f1a0f',
    marginHorizontal: 12,
    borderRadius: 9,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  xpBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#3d8b52',
    borderRadius: 9,
  },
  xpLabel: { fontSize: 10, color: 'rgba(255,255,255,0.5)', textAlign: 'center', letterSpacing: 1 },
  catRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingVertical: 8 },
  catBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1e3020',
    alignItems: 'center',
  },
  catBtnActive: { backgroundColor: '#1e3020', borderColor: '#3d8b52' },
  catText: { fontSize: 12, color: 'rgba(255,255,255,0.4)' },
  catTextActive: { color: '#5aad6a', fontWeight: '500' },
  mapControls: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingTop: 8 },
  mapWrapper: { margin: 12, borderRadius: 16, overflow: 'hidden', position: 'relative' },
  mapInner: { flex: 1 },
  mapResourceOverlay: {
    position: 'absolute',
    top: 6,
    left: 10,
    right: 60,
    zIndex: 6,
    pointerEvents: 'box-none',
  },
  mapResourceOverlayScroll: {
    maxWidth: '100%',
  },
  mapResourceOverlayScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexDirection: 'row',
  },
  mapResourcesChipsShell: {
    backgroundColor: 'rgba(12, 18, 12, 0.82)',
    borderRadius: 999,
    paddingVertical: 5,
    paddingLeft: 8,
    paddingRight: 10,
    borderWidth: 1,
    borderColor: 'rgba(30, 48, 32, 0.95)',
    maxWidth: '100%',
  },
  resourcesStripOnMap: {
    paddingHorizontal: 0,
    paddingBottom: 0,
    gap: 5,
  },
  mapBtn: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1e3020',
    backgroundColor: '#0f1a0f',
  },
  mapBtnActive: { borderColor: '#3d8b52', backgroundColor: '#1e3020' },
  mapBtnActive3D: { borderColor: '#e8c97a', backgroundColor: '#2a2010' },
  mapBtnText: { fontSize: 16 },
  creaturePopup: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: '#0f1a0f',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2d6a3f',
    zIndex: 100,
  },
  creatureEmoji: { fontSize: 52, marginBottom: 8 },
  creatureName: { fontSize: 18, color: '#e8e4d8', fontWeight: '500', marginBottom: 4 },
  creatureReward: { fontSize: 14, color: '#e8c97a', marginBottom: 16 },
  creatureBtn: {
    backgroundColor: '#2d6a3f',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 32,
    marginBottom: 8,
  },
  creatureBtnText: { color: 'white', fontSize: 15, fontWeight: '600' },
  feedingBarBg: {
    width: '100%',
    height: 8,
    backgroundColor: '#1e3020',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 12,
  },
  feedingBarFill: { height: '100%', backgroundColor: '#5aad6a', borderRadius: 4 },
  streak: { fontSize: 11, color: '#e8c97a', marginTop: 2, letterSpacing: 1 },
  mindfulBox: {
    backgroundColor: 'rgba(45,106,63,0.08)',
    borderLeftWidth: 2,
    borderLeftColor: '#3d8b52',
    borderRadius: 4,
    padding: 14,
    marginBottom: 20,
    width: '100%',
  },
  mindfulText: { fontSize: 13, color: 'rgba(255,255,255,0.5)', lineHeight: 20, fontStyle: 'italic' },
  newQuestsText: { color: '#e8e4d8', fontSize: 16 },
  resourcesStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 8,
    gap: 6,
  },
  resourcePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#0f1a0f',
    borderWidth: 1,
    borderColor: '#1e3020',
    gap: 4,
  },
  resourceEmoji: {
    fontSize: 14,
  },
  resourceText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
  },
  devGeoHint: {
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(246,188,64,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(246,188,64,0.35)',
  },
  devGeoHintText: {
    color: '#f6bc40',
    fontSize: 11,
    letterSpacing: 0.3,
  },
  devDock: {
    position: 'absolute',
    right: 14,
    bottom: 18,
    zIndex: 120,
  },
  devBtn: {
    backgroundColor: '#3b235a',
    borderColor: '#8a4df3',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  devBtnText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  devPanel: {
    position: 'absolute',
    right: 14,
    bottom: 64,
    zIndex: 120,
    backgroundColor: '#101510',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e3020',
    padding: 8,
    gap: 6,
    minWidth: 130,
  },
  devPanelBtn: {
    backgroundColor: '#1e3020',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  devPanelBtnActive: {
    borderWidth: 1,
    borderColor: '#e8c97a',
    backgroundColor: '#2a2415',
  },
  devPanelBtnDanger: {
    backgroundColor: '#5c1f1f',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  cardLocked: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15,26,15,0.5)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(30,48,32,0.5)',
    opacity: 0.55,
  },
  cardTitleLocked: { fontSize: 15, color: 'rgba(232,228,216,0.5)', fontWeight: '500' },
  cardRewardLocked: { fontSize: 13, color: 'rgba(232,201,122,0.4)', fontWeight: '600' },
  dropToast: {
    position: 'absolute',
    bottom: 90,
    alignSelf: 'center',
    backgroundColor: '#1a2a1a',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#3d8b52',
    zIndex: 200,
  },
  dropToastText: { color: '#e8e4d8', fontSize: 14, fontWeight: '500' },
  devPanelBtnText: {
    color: '#e8e4d8',
    fontSize: 12,
    textAlign: 'center',
  },
});
